version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      default:
        aliases:
          - resource-provider.localhost.yarf.nl
          - resource-provider-api.localhost.yarf.nl
          - identity.localhost.yarf.nl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
      - resource-provider
      - resource-provider-api

  keycloak:
    image: jboss/keycloak:4.8.3.Final         # Pinned to 4.8.3 because this is currently the latest version which has commercial support from Red Hat
    command: [
      "-b", "0.0.0.0",
      "-Dkeycloak.migration.action=import",   # Replace with 'export' in order to export everything
      "-Dkeycloak.migration.provider=dir",
      "-Dkeycloak.migration.dir=/opt/jboss/keycloak/standalone/configuration/export/",
      "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    ]
    environment:
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - KEYCLOAK_HOSTNAME=identity.localhost.yarf.nl
      # Legacy linking functionality is used
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=INFO
      - JAVA_TOOL_OPTIONS=-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled  # Required to enable Token exchange feature in newer versions of Keycloak
    volumes:
      - ./keycloak/export:/opt/jboss/keycloak/standalone/configuration/export
    networks:
      default:
        aliases:
          - keycloak

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    networks:
      default:
        aliases:
          - postgres

  resource-provider:
    build: ./resource-provider
    entrypoint: docker/entrypoint-dev.sh
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8001" ]
    volumes:
      - ./resource-provider:/usr/src/app
      - ./../:/usr/src/django-keycloak
      - ./../../python-keycloak-client:/usr/src/python-keycloak-client
      - ./nginx/certs/ca.pem:/usr/src/ca.pem
    networks:
      default:
        aliases:
          - resource-provider

  resource-provider-api:
    build: ./resource-provider-api
    entrypoint: docker/entrypoint-dev.sh
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8002" ]
    volumes:
      - ./resource-provider-api:/usr/src/app
      - ./../:/usr/src/django-keycloak
      - ./nginx/certs/ca.pem:/usr/src/ca.pem
    networks:
      default:
        aliases:
          - resource-provider-api