# Generated by Django 2.0.1 on 2018-01-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0002_nonce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonce',
            old_name='redirect_url',
            new_name='redirect_uri',
        ),
    ]
