# Generated by Django 2.0.1 on 2018-01-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0004_auto_20180121_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='keycloakopenidprofile',
            name='realm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_keycloak.Realm'),
            preserve_default=False,
        ),
    ]
