# Generated by Django 2.0.1 on 2018-01-28 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0005_keycloakopenidprofile_realm'),
    ]

    operations = [
        migrations.AddField(
            model_name='keycloakopenidprofile',
            name='expires_before',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 11, 0, 24, 177720, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keycloakopenidprofile',
            name='refresh_expires_before',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 11, 0, 30, 363283, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keycloakopenidprofile',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openid_profiles', to='django_keycloak.Realm'),
        ),
    ]
