# Generated by Django 2.0.1 on 2018-01-28 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0006_auto_20180128_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakopenidprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
