# Generated by Django 2.0.1 on 2018-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0007_auto_20180128_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonce',
            name='next_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
