# Generated by Django 2.0.1 on 2018-01-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0008_nonce_next_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='internal_server_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='server_url',
            field=models.CharField(default='https://keycloak.localhost.yarf.nl', max_length=255),
            preserve_default=False,
        ),
    ]
