# Generated by Django 2.0.1 on 2018-02-01 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_keycloak', '0009_auto_20180128_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='django_keycloak.Realm')),
            ],
        ),
        migrations.AddField(
            model_name='realm',
            name='content_types',
            field=models.ManyToManyField(through='django_keycloak.Resource', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('realm', 'content_type')},
        ),
    ]
