# Generated by Django 2.0.1 on 2018-02-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0010_auto_20180201_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='expires_before',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='refresh_expires_before',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keycloakopenidprofile',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keycloakopenidprofile',
            name='expires_before',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='keycloakopenidprofile',
            name='refresh_expires_before',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='keycloakopenidprofile',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
    ]
