# Generated by Django 2.0.2 on 2018-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0011_auto_20180201_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='well_known',
        ),
        migrations.AddField(
            model_name='realm',
            name='_well_known_oidc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='_well_known_uma',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='internal_server_url',
            field=models.CharField(help_text='URL on internal netwerk calls. For example when used with Docker Compose. Only supply when internal calls should go to a different url as the end-user will communicate with.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='name',
            field=models.CharField(help_text='Name as known on the Keycloak server. This name is used in the API paths of this Realm.', max_length=255, unique=True),
        ),
    ]
