# Generated by Django 2.0.2 on 2018-02-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0012_auto_20180205_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realm',
            old_name='certs',
            new_name='_certs',
        ),
    ]
