# Generated by Django 2.0.3 on 2018-03-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangedtoken',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exchangedtoken',
            name='oidc_profile',
        ),
        migrations.RemoveField(
            model_name='exchangedtoken',
            name='remote_client',
        ),
        migrations.RemoveField(
            model_name='remoteclient',
            name='realm',
        ),
        migrations.DeleteModel(
            name='ExchangedToken',
        ),
        migrations.DeleteModel(
            name='RemoteClient',
        ),
    ]
